channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.3.1
- pip:
  - mlflow==2.5.0
  - cloudpickle==2.0.0
  - configparser==5.2.0
  - numpy==1.23.5
  - psutil==5.9.0
  - scikit-learn==1.1.1
  - scipy==1.10.0
  - databricks-feature-lookup==0.*
name: mlflow-env
